name 'zero_ten'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures zero_ten'
long_description 'Installs/Configures zero_ten'
version '0.1.0'
